test
bcgov/trust-over-ip-configurations pull request #152
Opened 2023-10-04 15:57 UTC by rajpalc7

2023-10-12 14:19 UTC, WadeBarnes requested changes
Overall this workflow is triggering on a schedule (as expected) and on any commits to the `main` branch regardless of whether the changes have anything to do with the traction instance.  This will cause unexpected and unwanted refreshes to the traction instance.  A filter should be added to ensure the action is only triggered when changes are directly related to the traction instance.

Also see the specific comments below.

2023-10-12 14:19 UTC, WadeBarnes commented on .github/workflows/uninstall_install_sandbox.yaml
> +          token: ${{ secrets.ROCKETCHAT_TOKEN }}
`token: ${{ secrets.ROCKETCHAT_TOKEN }}` is not required if the `secrets.ROCKETCHAT_WEBHOOK` contains the token, which in our case it does.  Refer to your previous work with this action here; https://github.com/bcgov/von-bc-registries-audit/blob/main/.github/workflows/actions/deploy/action.yml#L83-L93

2023-10-12 14:19 UTC, WadeBarnes commented on .github/workflows/uninstall_install_sandbox.yaml
> +          token: ${{ secrets.ROCKETCHAT_TOKEN }}
`token: ${{ secrets.ROCKETCHAT_TOKEN }}` is not required if the `secrets.ROCKETCHAT_WEBHOOK` contains the token, which in our case it does.  Refer to your previous work with this action here; https://github.com/bcgov/von-bc-registries-audit/blob/main/.github/workflows/actions/deploy/action.yml#L83-L93

2023-10-12 14:19 UTC, WadeBarnes commented on .github/workflows/uninstall_install_sandbox.yaml
> +        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@master
```suggestion
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@1.1.1
```
It's best practice to always target a released version of an action, that way you are not surprised by unexpected changes as you would be when targeting the `master` branch.  We covered this during your previous work with this action here; https://github.com/bcgov/von-bc-registries-audit/blob/main/.github/workflows/actions/deploy/action.yml#L83-L93

2023-10-12 14:19 UTC, WadeBarnes commented on .github/workflows/uninstall_install_sandbox.yaml
> +        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@master
```suggestion
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@1.1.1
```
It's best practice to always target a released version of an action, that way you are not surprised by unexpected changes as you would be when targeting the `master` branch.  We covered this during your previous work with this action here; https://github.com/bcgov/von-bc-registries-audit/blob/main/.github/workflows/actions/deploy/action.yml#L83-L93

2023-10-12 16:16 UTC, WadeBarnes commented
Example of path filters; https://github.com/hyperledger/indy-node/blob/main/.github/workflows/Push.yaml

2023-10-12 20:20 UTC, rajpalc7 commented
Thanks for the feedback wade, made the changes accordingly.

2023-10-13 16:46 UTC, WadeBarnes requested changes
Some comments below

2023-10-13 16:46 UTC, WadeBarnes commented on .github/workflows/uninstall_install_sandbox.yaml
> +      #     oc delete -n ${{ secrets.OPENSHIFT_NAMESPACE }} all,secret,pod,networkpolicy,configmap,pvc --selector "app.kubernetes.io/instance"=traction-sandbox
Did you mean to comment out the `Uninstall Traction via Helm` and `Remove Traction Openshift Objects` steps?

2023-10-13 17:01 UTC, WadeBarnes commented
That looks better @rajpalc7.  Please clean up the commit history.

2023-10-13 17:24 UTC, rajpalc7 commented
@WadeBarnes -  Commit history is cleaned up now

2023-10-13 17:29 UTC, WadeBarnes requested changes
Hey @rajpalc7, I'm a little confused over the changes made by the cleanup.  The previous commits were just updates to the one `.github/workflows/uninstall_install_sandbox.yaml` file.  With the most recent commit there are changes to two other files included and it's showing `.github/workflows/uninstall_install_sandbox.yaml` is being added as a new file.

What happened?

2023-10-13 17:50 UTC, rajpalc7 commented
@WadeBarnes that might be because of the git HEAD reset command .  It should have been git reset HEAD~6 instead of HEAD~7 . Let me know if you want me to create another PR just for this file

2023-10-13 18:31 UTC, rajpalc7 commented
https://github.com/bcgov/trust-over-ip-configurations/pull/159/commits - I was able to create a new PR for review

2023-10-13 18:35 UTC, WadeBarnes commented
The changes associated to this PR are being performed over here now; https://github.com/bcgov/trust-over-ip-configurations/pull/159

2023-10-13 18:42 UTC, WadeBarnes commented
This PR is being closed in favor of https://github.com/bcgov/trust-over-ip-configurations/pull/159

2023-10-13 18:42 UTC, closed without merging