chore: updating dependabot file to support gha, npm and docker packages
bcgov/trust-over-ip-configurations pull request #199
Opened 2024-04-26 22:12 UTC by rajpalc7

2024-04-26 22:47 UTC, rajpalc7 commented
Hi @WadeBarnes this is ready for review now

2024-04-29 13:09 UTC, WadeBarnes requested changes
You are missing an update section.

2024-04-29 15:50 UTC, rajpalc7 commented
@WadeBarnes added the section now

2024-04-29 17:47 UTC, WadeBarnes approved these changes

2024-04-29 17:47 UTC, merged